os:
  - linux
sudo: true
env:
  matrix:
  - TRAVIS_NODE_VERSION="11"
  - TRAVIS_NODE_VERSION="10"
  - TRAVIS_NODE_VERSION="9"
  - TRAVIS_NODE_VERSION="8"
  - TRAVIS_NODE_VERSION="6"
before_install:
  - sudo apt-get -qq update
  - wget http://swdownloads.analog.com/cse/travis_builds/master_latest_libiio-ubuntu-14.04-amd64.deb
  - sudo dpkg -i master_latest_libiio-trusty.deb
install:
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
  - npm --version
  - npm install
script: npm test
